export const response = {
  data: [
    {
      author: "Sudipto Maity",
      category: "sports",
      image:
        "https://image-cdn.essentiallysports.com/wp-content/uploads/WhatsApp-Image-2023-03-30-at-3.26.54-PM-394x315.jpeg",
      description:
        "Since his debut in 2002, Brock Lesnar has carved out a legacy for himself in the pro-wrestling business. There is never a dull moment when The Beast Incarnate is around as things could escalate quickly, as Cody Rhodes found out a few days ago. Lesnar&#8217;s betrayal and brutal beat down of Rhodes has left the&#8230;The post Having Attacked Cody Rhodes, Brock Lesnar Went Off Script to Address What He Does Not Want From His Current WWE Run appeared first on EssentiallySports.",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:00:23Z",
      source: "Essentially Sports",
      title:
        "Having Attacked Cody Rhodes, Brock Lesnar Went Off Script to Address What He Does Not Want From His Current WWE Run",
      url: "https://www.essentiallysports.com/wwe-news-having-attacked-cody-rhodes-brock-lesnar-went-off-script-to-address-what-he-does-not-want-from-his-current-wwe-run/",
    },
    {
      author: "Shannon Sullivan",
      category: "general",
      image: null,
      description:
        "Although&#160;Billie Eilish&#160;had company, collaborating with another artist for her latest musical efforts, the name of her new song was Never Felt So Alone. Billie joined forces with Labrinth, an established singer-songwriter from the UK whose music has appeared on HBO&#8217;s Euphoria. Together, the musicians created magic with a melody that",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:08:48Z",
      source: "monstersandcritics",
      title: "Billie Eilish unveils new music video with captivating visuals",
      url: "https://www.monstersandcritics.com/celebrity/billie-eilish-unveils-new-music-video-with-captivating-visuals/",
    },
    {
      author: "Staff",
      category: "general",
      image: null,
      description:
        "WebProNewsWalmart Is Relying on Automation, But Not to Replace WorkersWalmart is doubling down on its push for automation, but CEO and President Doug McMillon says workers have no reason to fear losing their jobs.Walmart Is Relying on Automation, But Not to Replace WorkersStaff",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:08:05Z",
      source: "webpronews",
      title: "Walmart Is Relying on Automation, But Not to Replace Workers",
      url: "https://www.webpronews.com/walmart-is-relying-on-automation-but-not-to-replace-workers/",
    },
    {
      author: "J.J. Adams",
      category: "general",
      image: null,
      description:
        "The Vancouver Whitecaps striker did everything but score in his team's early games, but now he's finding the back of the net as well, just when they need him most.",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:07:20Z",
      source: "theprovince",
      title:
        "Whitecaps striker Brian White is back, but the truth is he never left",
      url: "https://theprovince.com/sports/soccer/mls/vancouver-whitecaps/striker-brian-white-back-but-truth-is-he-never-left",
    },
    {
      author: "wtopstaff",
      category: "general",
      image: null,
      description:
        "OCALA, Fla. (AP) — A 16-year-old boy wanted as part of an investigation into the killings of three teenagers in&#8230;",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:05:43Z",
      source: "wtop",
      title: "Suspect arrested in Florida after killings of 3 teens",
      url: "https://wtop.com/national/2023/04/suspect-arrested-in-florida-after-killings-of-3-teens/",
    },
    {
      author: null,
      category: "general",
      image: null,
      description: "Suspect arrested in Florida after killings of 3 teens",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:05:41Z",
      source: "Yahoo News",
      title: "Suspect arrested in Florida after killings of 3 teens",
      url: "https://news.yahoo.com/suspect-arrested-florida-killings-3-180541534.html",
    },
    {
      author: "Caroline Michailoff",
      category: "general",
      image: null,
      description:
        "At this year’s annual Dragon Day event, architecture students emphasized sustainability through building a dragon model out of recycled materials.",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:05:35Z",
      source: "cornellsun",
      title: "Dragon Day Scales Up Sustainability Emphasis in Annual Parade",
      url: "https://cornellsun.com/2023/04/02/dragon-day-scales-up-sustainability-emphasis-in-annual-parade/",
    },
    {
      author: "Vince Mancini",
      category: "general",
      image: null,
      description:
        "David Moir/Bravo This week on Top Chef World All-Stars, the chefs had to pair an app with mead and then cook up a pot luck fit for a VRBO.",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:05:13Z",
      source: "hitfix",
      title:
        "Top Chef World All-Stars Power Rankings, Week 5: Mead The Fockers",
      url: "https://uproxx.com/life/top-chef-world-all-stars-rankings-week-5/",
    },
    {
      author: null,
      category: "general",
      image: null,
      description: "5th grader raises $2,000 for grieving teacher",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:05:04Z",
      source: "CNN US",
      title: "5th grader raises $2,000 for grieving teacher",
      url: "https://www.ketv.com/article/ralston-she-was-going-through-a-lot-5th-grader-raises-2000-for-grieving-teacher/42115993",
    },
    {
      author: "Andrew Bucholtz",
      category: "general",
      image: null,
      description:
        "One of the more unusual occurrences in a post-game TV interview in a while came after the Quinnipiac Bobcats completed a comeback to win the NCAA men&#8217;s hockey national title. Quinnipiac trailed the Minnesota Golden Gophers 2-1 with 3:28 left, and that led to head coach Rand Pecknold making the bold move to pull his Read more...The post Qunnipiac coach asks for, gets hug from reporter in post-championship interview appeared first on Awful Announcing.",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:04:50Z",
      source: "awfulannouncing",
      title:
        "Qunnipiac coach asks for, gets hug from reporter in post-championship interview",
      url: "https://awfulannouncing.com/ncaa/qunnipiac-rand-pecknold-hug-colby-cohen.html",
    },
    {
      author: "James Walker",
      category: "general",
      image: null,
      description: "How To Remove Icons From Your iPad Home Screen",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:04:47Z",
      source: "devicemag",
      title: "How To Remove Icons From Your iPad Home Screen",
      url: "https://www.devicemag.com/how-to-remove-icons-from-ipad-home-screen/",
    },
    {
      author: "James Walker",
      category: "general",
      image: null,
      description: "How To Remove Homepod From Your iPhone",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:04:47Z",
      source: "devicemag",
      title: "How To Remove Homepod From Your iPhone",
      url: "https://www.devicemag.com/how-to-remove-homepod-from-iphone/",
    },
    {
      author: "James Walker",
      category: "general",
      image: null,
      description: "NordVPN vs PureVPN: Which is the Best Fit for You?",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:04:14Z",
      source: "devicemag",
      title: "NordVPN vs PureVPN: Which is the Best Fit for You?",
      url: "https://www.devicemag.com/purevpn-vs-nordvpn/",
    },
    {
      author: "CNN Newssource",
      category: "general",
      image: null,
      description:
        "By Dakin Andone and Rebekah Riess, CNN The union representing thousands of Los Angeles school workers has voted &#8220;overwhelmingly&#8221; to approve a new contract with the Los Angeles Unified School District after last month&#8217;s three-day strike, union officials said in a news release Saturday. More than 99% of Service Employees International Union Local 99 membersThe post Los Angeles school workers&#8217; union votes to approve new contract with school district appeared first on KRDO.",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:02:25Z",
      source: "krdo",
      title:
        "Los Angeles school workers’ union votes to approve new contract with school district",
      url: "https://krdo.com/news/2023/04/09/los-angeles-school-workers-union-votes-to-approve-new-contract-with-school-district/",
    },
    {
      author: "Jonathan Mattise The Associated Press",
      category: "general",
      image: null,
      description:
        "The expulsions have made Tennessee a new front in the battle for the future of American democracy.",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:02:24Z",
      source: "lvrj",
      title: "Expelled Tennessee lawmakers both seeking seats again",
      url: "https://www.reviewjournal.com/news/politics-and-government/expelled-tennessee-lawmakers-both-seeking-seats-again-2759225/",
    },
    {
      author: "The Associated Press",
      category: "general",
      image: null,
      description:
        "LETHEM, Guyana (AP) &#8212; Their horses&#8217; hooves kick up dust amid blaring country music as participants enter the arena to begin the Rupununi Ranchers Rodeo, a celebration of the cowboy lifestyle on Guyana&#8217;s rugged Rupununi savannah. The two-day, annual rodeo draws thousands of visitors from Guyana&#8217;s capital and other countries, especially neighboring Brazil. The event [&#8230;]",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:01:02Z",
      source: "nationalpost",
      title: "Guyana’s Rupununi Rodeo celebrates local cowboy culture",
      url: "https://nationalpost.com/pmn/news-pmn/guyanas-rupununi-rodeo-celebrates-local-cowboy-culture",
    },
    {
      author: "ktherriault",
      category: "general",
      image: null,
      description:
        "Beginning April 1, 2023, St. Lawrence College (SLC) along with all of Ontario’s 24 colleges, will offer a new pathway for Personal Support Workers (PSWs) who wish to qualify to practice…L’article St. Lawrence College Will Offer Personal Support Worker to Practical Nurse Upgrading Courses est apparu en premier sur Cornwall Seaway News.",
      country: "us",
      language: "en",
      published_at: "2023-04-09T18:00:55Z",
      source: "cornwallseawaynews",
      title:
        "St. Lawrence College Will Offer Personal Support Worker to Practical Nurse Upgrading Courses",
      url: "https://www.cornwallseawaynews.com/education/st-lawrence-college-will-offer-personal-support-worker-to-practical-nurse-upgrading-courses/",
    },
  ],
};
