import "../styles/globals.css";
import Header from "./Header";
import Providers from "./Providers";


export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className="bg-gray-100 dark:bg-zinc-900 text-gray-900 dark:text-gray-100 transition-all duration-700">
          <Header />
          <div className="mx-auto max-w-6xl">{children}</div>
        </body>
      </Providers>
    </html>
  );
}
